import React from "react";
import { Row, Divider, Typography} from "antd";

const { Title, Paragraph, Text } = Typography;

export default () => (
  <>
    <Row id="Musician" align="center">
      <Typography>
        <Title>Music</Title>
        <Paragraph style={{ maxWidth: "1024px" }}>
            I was born with a <i>perfect pitch</i>: If you play any note from an instrument, I can instantly recognize it because
            what I hear is not sond, but the name of the note. 
            This might seem like a super power, and while it is quite useful for the creation of music, it does impact the quality of life.
            Because, I tend to be quite sensitive to sounds generated by humans and nature. 
            I had to actively employ Mindfulness in order to calm my <i>fight and flight</i> response whenever I heard annoying sounds.
        </Paragraph>
        <Paragraph style={{ maxWidth: "1024px" }}>
            My grand mother taught me how to play the piano from a very young age. I studied at the conservatory, and eventually got bored 
            of classical music, and switched to Jazz. Later on, I explored music composition using Ableton Live.
        </Paragraph>
      </Typography>
      <Divider style={{ margin: "100px 0",borderColor: "#d2d2d2" }} />
    </Row>
  </>
);
